const WORDS = [
  // 3 letters
  { word: "ssh",       hint: "Opens an encrypted channel to a remote machine over the network" },
  { word: "vim",       hint: "A modal terminal text editor with decades of history" },
  { word: "top",       hint: "Watches running processes and CPU usage in real time" },
  { word: "php",       hint: "Server-side scripting engine often paired with Apache" },
  { word: "awk",       hint: "Pattern-scanning and text-processing language for columnar data" },
  { word: "sed",       hint: "Reads a stream of text and applies editing commands to each line" },
  { word: "tar",       hint: "Bundles multiple files into a single archive file" },
  { word: "gdb",       hint: "An interactive debugger for stepping through and inspecting running programs" },
  { word: "git",       hint: "Tracks changes to files and coordinates work across a team" },
  { word: "tee",       hint: "Reads from stdin and simultaneously writes to stdout and a file" },
  { word: "man",       hint: "Displays the reference manual page for any command or system call" },
  { word: "cut",       hint: "Extracts specific columns or fields from each line of text" },
  { word: "who",       hint: "Shows which users are currently logged into the system" },
  { word: "gdm",       hint: "The GNOME display manager that handles graphical login screens" },
  { word: "zsh",       hint: "A feature-rich interactive shell popular with power users" },
  { word: "rpm",       hint: "Manages software packages on Red Hat-based Linux distributions" },
  { word: "apt",       hint: "Installs, updates, and removes packages on Debian-based systems" },
  { word: "dnf",       hint: "The next-generation package manager for Fedora and RHEL" },
  { word: "yum",       hint: "An older package manager for Red Hat-based Linux distributions" },
  { word: "tor",       hint: "Routes internet traffic through volunteer relays to anonymise the user" },
  { word: "gpg",       hint: "Encrypts and signs data using public-key cryptography" },
  { word: "lsm",       hint: "The Windows process that manages local user sessions after login" },

  // 4 letters
  { word: "bash",      hint: "The default interactive shell on most Linux systems" },
  { word: "grep",      hint: "Searches text streams using regular expressions" },
  { word: "curl",      hint: "Transfers data to or from a server via URL" },
  { word: "ping",      hint: "Tests whether a remote host is reachable on the network" },
  { word: "sudo",      hint: "Executes a command with superuser privileges" },
  { word: "cron",      hint: "Runs scheduled tasks at specified times automatically" },
  { word: "less",      hint: "A pager that lets you scroll through file contents in the terminal" },
  { word: "nano",      hint: "A beginner-friendly terminal text editor" },
  { word: "find",      hint: "Recursively locates files and directories matching given criteria" },
  { word: "sort",      hint: "Arranges lines of text from stdin into a specified order" },
  { word: "diff",      hint: "Shows line-by-line differences between two files" },
  { word: "make",      hint: "Automates building software from source code using a ruleset" },
  { word: "perl",      hint: "A scripting language famous for powerful text processing" },
  { word: "ruby",      hint: "An object-oriented interpreted scripting language from Japan" },
  { word: "sshd",      hint: "Listens for incoming encrypted remote-login connections" },
  { word: "doas",      hint: "A minimal privilege escalation tool, an alternative to another well-known command" },
  { word: "kill",      hint: "Sends a signal to a process, often used to terminate it" },
  { word: "nmap",      hint: "Scans networks to discover open ports and running services" },
  { word: "fish",      hint: "A user-friendly interactive shell with smart autosuggestions" },
  { word: "tmux",      hint: "Terminal multiplexer for managing multiple persistent sessions" },
  { word: "wget",      hint: "Downloads files from the web non-interactively" },
  { word: "htop",      hint: "An interactive, colorful process viewer with mouse support" },
  { word: "init",      hint: "The first process the kernel starts at boot; ancestor of all others" },
  { word: "lsof",      hint: "Lists all open files and the processes currently using them" },
  { word: "tail",      hint: "Outputs the last lines of a file, commonly used to follow logs" },
  { word: "wall",      hint: "Broadcasts a message to all currently logged-in users" },
  { word: "more",      hint: "A simple pager for reading file output one screen at a time" },
  { word: "fsck",      hint: "Checks and repairs inconsistencies in a filesystem" },
  { word: "jobs",      hint: "Lists background and stopped jobs in the current shell session" },
  { word: "nice",      hint: "Launches a process with a manually specified scheduling priority" },
  { word: "date",      hint: "Displays or sets the system clock and calendar date" },
  { word: "chsh",      hint: "Changes the login shell assigned to a user account" },
  { word: "tcpd",      hint: "Wraps network services to enforce host-based access control" },
  { word: "smss",      hint: "The first user-mode process Windows starts; manages sessions and creates the login environment" },
  { word: "aide",      hint: "Builds a database of file hashes to detect unauthorized changes" },

  // 5 letters
  { word: "nginx",     hint: "Serves web traffic and proxies requests at high speed" },
  { word: "uname",     hint: "Reports the operating system name and kernel version" },
  { word: "mount",     hint: "Attaches a storage device to the filesystem directory tree" },
  { word: "sleep",     hint: "Suspends execution for a given number of seconds" },
  { word: "touch",     hint: "Creates an empty file or updates its access timestamp" },
  { word: "alias",     hint: "Defines a shorthand name for a longer shell command" },
  { word: "shred",     hint: "Overwrites a file multiple times to prevent data recovery" },
  { word: "rsync",     hint: "Efficiently synchronizes files between two locations" },
  { word: "chown",     hint: "Changes the ownership of a file or directory" },
  { word: "chmod",     hint: "Modifies the read, write, and execute permissions of a file" },
  { word: "dmesg",     hint: "Prints messages from the kernel ring buffer after boot" },
  { word: "nohup",     hint: "Runs a command that stays alive after the terminal closes" },
  { word: "xargs",     hint: "Constructs and executes commands from lines of standard input" },
  { word: "emacs",     hint: "A highly extensible programmer's text editor and computing environment" },
  { word: "httpd",     hint: "The generic HTTP server daemon process name" },
  { word: "xterm",     hint: "A terminal emulator window for the X Window System" },
  { word: "lsblk",     hint: "Lists block storage devices and their partition hierarchy" },
  { word: "udevd",     hint: "The Linux kernel device manager daemon that handles hotplug events" },
  { word: "crond",     hint: "The daemon that reads crontab files and fires scheduled jobs" },
  { word: "fwupd",     hint: "Updates device firmware on Linux systems in the background" },
  { word: "inetd",     hint: "The original internet super-server that spawns other daemons on demand" },
  { word: "acpid",     hint: "Listens for ACPI hardware events like power button and lid close" },
  { word: "route",     hint: "Displays or modifies the kernel IP routing table" },
  { word: "unzip",     hint: "Extracts files from a ZIP archive" },
  { word: "whois",     hint: "Queries registration information for a domain name or IP address" },
  { word: "blkid",     hint: "Identifies block devices and reports their filesystem types and UUIDs" },
  { word: "ifcfg",     hint: "Configures or displays network interface parameters" },
  { word: "lsass",     hint: "Enforces Windows security policy and handles all login authentication" },
  { word: "csrss",     hint: "A critical Windows process that manages console windows and process/thread operations" },
  { word: "clamd",     hint: "The background scanning daemon of a popular open-source antivirus engine" },
  { word: "snort",     hint: "Analyses network packets in real time to detect intrusion attempts" },
  { word: "falco",     hint: "Monitors system calls at runtime to detect unexpected container or process behaviour" },
  { word: "vault",     hint: "Securely stores and tightly controls access to secrets, tokens, and certificates" },
  { word: "ossec",     hint: "A host-based intrusion detection system that monitors logs and file integrity" },
  { word: "wazuh",     hint: "An open-source security platform for threat detection and incident response" },

  // 6 letters
  { word: "python",    hint: "An interpreted language beloved for its readable syntax" },
  { word: "mysqld",    hint: "The server daemon for a popular open-source relational database" },
  { word: "passwd",    hint: "Lets a user update their login credentials" },
  { word: "screen",    hint: "Keeps terminal sessions alive after you disconnect" },
  { word: "strace",    hint: "Intercepts and records system calls made by a running process" },
  { word: "renice",    hint: "Adjusts the CPU scheduling priority of a running process" },
  { word: "uptime",    hint: "Reports how long the system has been running and current load" },
  { word: "logout",    hint: "Terminates the current user session and closes the shell" },
  { word: "auditd",    hint: "Records security-relevant system events for compliance and forensics" },
  { word: "vmstat",    hint: "Reports virtual memory, CPU, and I/O statistics at a glance" },
  { word: "iostat",    hint: "Shows CPU and disk I/O statistics over time" },
  { word: "polkit",    hint: "Manages authorization requests for privileged system operations" },
  { word: "xinetd",    hint: "An extended internet super-server daemon with fine-grained access control" },
  { word: "syslog",    hint: "Collects and stores system log messages from the kernel and daemons" },
  { word: "puppet",    hint: "Automates configuration management and system state enforcement" },
  { word: "cronie",    hint: "A modern implementation of the cron job scheduling daemon" },
  { word: "dhcpcd",    hint: "A DHCP client daemon that automatically configures network interfaces" },
  { word: "smartd",    hint: "Monitors hard drive health using S.M.A.R.T. diagnostics in the background" },
  { word: "swapon",    hint: "Activates a swap partition or file for use as virtual memory" },
  { word: "wermgr",   hint: "Collects Windows crash data and sends error reports to Microsoft" },

  // 7 letters
  { word: "systemd",   hint: "The init system responsible for booting and managing services on modern Linux" },
  { word: "apache2",   hint: "The world's most widely deployed open-source HTTP server process" },
  { word: "svchost",   hint: "A Windows host process that loads multiple DLL-based services" },
  { word: "crontab",   hint: "Edits the table of scheduled recurring automated jobs" },
  { word: "netstat",   hint: "Displays open network connections and listening ports" },
  { word: "rsyslog",   hint: "Collects, filters, and forwards system log messages" },
  { word: "dockerd",   hint: "The background daemon that manages containers and images" },
  { word: "dnsmasq",   hint: "A lightweight DNS forwarder and DHCP server for small networks" },
  { word: "postfix",   hint: "A widely used mail transfer agent for routing and delivering email" },
  { word: "chronyd",   hint: "Keeps the system clock accurately synchronized using NTP" },
  { word: "haproxy",   hint: "A high-performance load balancer for TCP and HTTP traffic" },
  { word: "mariadb",   hint: "The community-developed fork of a popular relational database server" },
  { word: "mongodb",   hint: "A NoSQL document-oriented database server process" },
  { word: "jenkins",   hint: "An open-source automation server for CI/CD pipelines" },
  { word: "grafana",   hint: "A visualization and dashboarding platform for metrics and logs" },
  { word: "kubelet",   hint: "The primary node agent running on each Kubernetes worker node" },
  { word: "autossh",   hint: "Automatically restarts SSH tunnels that drop due to connection issues" },
  { word: "syslogd",   hint: "The traditional Unix daemon that receives and stores system log messages" },
  { word: "lvmetad",   hint: "Caches LVM metadata to speed up volume group activation" },
  { word: "rpcbind",   hint: "Maps RPC program numbers to their network port numbers" },
  { word: "tcpdump",   hint: "Captures raw network packets and displays or saves them for analysis" },
  { word: "openvpn",   hint: "Creates encrypted tunnels between hosts using SSL/TLS" },
  { word: "spoolsv",   hint: "Manages the Windows print queue; frequently targeted in privilege escalation attacks" },
  { word: "stunnel",   hint: "Wraps unencrypted TCP connections inside a TLS tunnel" },
  { word: "openssl",   hint: "A toolkit for SSL/TLS and general-purpose cryptography" },
  { word: "taskmgr",   hint: "The Windows utility for monitoring and killing running processes" },
  { word: "certbot",   hint: "Automatically obtains and renews TLS certificates from a certificate authority" },
  { word: "nessusd",   hint: "The daemon process behind a widely used commercial vulnerability scanner" },
  { word: "openvas",   hint: "The scanner daemon for an open-source vulnerability assessment framework" },

  // 8 letters
  { word: "explorer",  hint: "The Windows graphical desktop shell and file manager" },
  { word: "postgres",  hint: "The backend server process of a popular object-relational database" },
  { word: "chromium",  hint: "The open-source browser engine that powers many modern browsers" },
  { word: "winlogon",  hint: "Handles the Windows secure attention sequence and user login" },
  { word: "iptables",  hint: "Configures the Linux kernel netfilter firewall packet filtering rules" },
  { word: "rabbitmq",  hint: "An Erlang-based message broker and queue server for distributed systems" },
  { word: "dhclient",  hint: "Requests an IP address and network configuration from a DHCP server" },
  { word: "wineboot",  hint: "Initializes and simulates a Windows boot sequence inside the compatibility layer" },
  { word: "svnserve",  hint: "The standalone server daemon for Subversion version control repositories" },
  { word: "nftables",  hint: "The modern Linux packet filtering framework that replaces iptables" },
  { word: "apparmor",  hint: "Confines programs to a limited set of resources using per-process security profiles" },
  { word: "suricata",  hint: "A high-performance network intrusion detection, prevention, and monitoring engine" },
  { word: "rkhunter",  hint: "Scans for rootkits, backdoors, and suspicious local exploits" },
  { word: "tripwire",  hint: "Detects unauthorised file changes by comparing against a known-good baseline" },
  { word: "seclogon",  hint: "A Windows service that allows processes to be started under different credentials" },
  { word: "ntoskrnl",  hint: "The core Windows kernel image responsible for hardware abstraction and system calls" },

  // 9 letters
  { word: "memcached",  hint: "Stores frequently accessed data in memory to reduce database load" },
  { word: "firewalld",  hint: "The dynamic firewall management daemon on modern Linux systems" },
  { word: "logrotate",  hint: "Rotates, compresses, and manages old log files automatically" },
  { word: "wireshark",  hint: "Captures and dissects network packets with a rich protocol analyser" },
  { word: "windefend",  hint: "The Windows Defender antivirus service that scans for malware in real time" },
  { word: "wireguard",  hint: "A modern, high-performance VPN protocol built into the Linux kernel" },

  // 10 letters
  { word: "keepalived",  hint: "Provides high availability and load balancing via VRRP" },
  { word: "containerd",  hint: "The industry-standard container runtime used by Docker and Kubernetes" },
  { word: "pulseaudio",  hint: "The sound server daemon that routes audio between applications on Linux" },
];
