const WORDS = [
  // 3 letters
  { word: "ssh",       hint: "Opens an encrypted channel to a remote machine over the network" },
  { word: "vim",       hint: "A modal terminal text editor with decades of history" },
  { word: "top",       hint: "Watches running processes and CPU usage in real time" },
  { word: "php",       hint: "Server-side scripting engine often paired with Apache" },
  { word: "awk",       hint: "Pattern-scanning and text-processing language for columnar data" },
  { word: "sed",       hint: "Reads a stream of text and applies editing commands to each line" },
  { word: "tar",       hint: "Bundles multiple files into a single archive file" },
  { word: "gdb",       hint: "An interactive debugger for stepping through and inspecting running programs" },
  { word: "git",       hint: "Tracks changes to files and coordinates work across a team" },
  { word: "tee",       hint: "Reads from stdin and simultaneously writes to stdout and a file" },
  { word: "man",       hint: "Displays the reference manual page for any command or system call" },
  { word: "cut",       hint: "Extracts specific columns or fields from each line of text" },
  { word: "who",       hint: "Shows which users are currently logged into the system" },
  { word: "gdm",       hint: "The GNOME display manager that handles graphical login screens" },
  { word: "zsh",       hint: "A feature-rich interactive shell popular with power users" },
  { word: "rpm",       hint: "Manages software packages on Red Hat-based Linux distributions" },
  { word: "apt",       hint: "Installs, updates, and removes packages on Debian-based systems" },
  { word: "dnf",       hint: "The next-generation package manager for Fedora and RHEL" },
  { word: "yum",       hint: "An older package manager for Red Hat-based Linux distributions" },
  { word: "tor",       hint: "Routes internet traffic through volunteer relays to anonymise the user" },
  { word: "gpg",       hint: "Encrypts and signs data using public-key cryptography" },
  { word: "lsm",       hint: "The Windows process that manages local user sessions after login" },
  { word: "cat",       hint: "Reads files sequentially and writes their contents to standard output" },
  { word: "env",       hint: "Displays current environment variables or runs a command with modified ones" },
  { word: "pwd",       hint: "Prints the absolute path of the current working directory" },
  { word: "dig",       hint: "Queries DNS name servers and displays detailed record information" },
  { word: "yes",       hint: "Outputs an affirmative string over and over until it is killed" },
  { word: "tty",       hint: "Prints the file name of the terminal connected to standard input" },
  { word: "cal",       hint: "Displays a neatly formatted calendar for the current or specified month" },
  { word: "seq",       hint: "Prints a sequence of numbers from a starting value to an ending value" },
  { word: "rev",       hint: "Reverses each line of input character by character" },
  { word: "cmd",       hint: "The default command-line interpreter shell on Windows systems" },
  { word: "dwm",       hint: "The Windows process that composites and renders all desktop visual effects" },
  { word: "scp",       hint: "Copies files between hosts over an encrypted SSH connection" },
  { word: "arp",       hint: "Displays and modifies the system's IP-to-MAC address resolution table" },
  { word: "fmt",       hint: "Reformats text paragraphs to fit a given line width" },
  { word: "wsl",       hint: "Launches a Linux environment directly inside Windows" },
  { word: "adb",       hint: "A bridge tool for communicating with and debugging Android devices" },
  { word: "xev",       hint: "Displays X11 events like keypresses and mouse clicks in real time" },
  { word: "ldd",       hint: "Prints the shared libraries required by an executable program" },
  { word: "npm",       hint: "The default package manager for the Node.js ecosystem" },
  { word: "gcc",       hint: "The GNU compiler that translates C source code into executables" },
  { word: "sfc",       hint: "The Windows System File Checker that scans for and restores corrupted OS files" },
  { word: "ftp",       hint: "A command-line client for transferring files to and from remote servers" },
  { word: "xxd",       hint: "Creates a hex dump of a file or reverses a hex dump back to binary" },
  { word: "lvs",       hint: "Displays information about LVM logical volumes in a compact summary" },
  { word: "svn",       hint: "The Subversion version control client for tracking changes to files" },
  { word: "avp",       hint: "The main Kaspersky antivirus process that handles real-time threat protection" },
  { word: "kvm",       hint: "The Linux kernel module that turns the processor into a bare-metal hypervisor" },
  { word: "lxc",       hint: "A lightweight Linux container runtime that isolates processes without a full VM" },
  { word: "pct",       hint: "The Proxmox command-line tool for creating and managing LXC containers" },
  { word: "rbd",       hint: "Maps Ceph distributed storage as a local block device for VMs to use" },
  { word: "zfs",       hint: "An advanced filesystem and volume manager with built-in snapshots and checksums" },
  { word: "vmx",       hint: "The ESXi process that runs each virtual machine's execution context" },
  { word: "fdm",       hint: "The VMware HA Fault Domain Manager agent on each ESXi host" },
  { word: "eam",       hint: "The vCenter ESX Agent Manager that deploys partner solutions to hosts" },

  // 4 letters
  { word: "bash",      hint: "The default interactive shell on most Linux systems" },
  { word: "grep",      hint: "Searches text streams using regular expressions" },
  { word: "curl",      hint: "Transfers data to or from a server via URL" },
  { word: "ping",      hint: "Tests whether a remote host is reachable on the network" },
  { word: "sudo",      hint: "Executes a command with superuser privileges" },
  { word: "cron",      hint: "Runs scheduled tasks at specified times automatically" },
  { word: "less",      hint: "A pager that lets you scroll through file contents in the terminal" },
  { word: "nano",      hint: "A beginner-friendly terminal text editor" },
  { word: "find",      hint: "Recursively locates files and directories matching given criteria" },
  { word: "sort",      hint: "Arranges lines of text from stdin into a specified order" },
  { word: "diff",      hint: "Shows line-by-line differences between two files" },
  { word: "make",      hint: "Automates building software from source code using a ruleset" },
  { word: "perl",      hint: "A scripting language famous for powerful text processing" },
  { word: "ruby",      hint: "An object-oriented interpreted scripting language from Japan" },
  { word: "sshd",      hint: "Listens for incoming encrypted remote-login connections" },
  { word: "doas",      hint: "A minimal privilege escalation tool, an alternative to another well-known command" },
  { word: "kill",      hint: "Sends a signal to a process, often used to terminate it" },
  { word: "nmap",      hint: "Scans networks to discover open ports and running services" },
  { word: "fish",      hint: "A user-friendly interactive shell with smart autosuggestions" },
  { word: "tmux",      hint: "Terminal multiplexer for managing multiple persistent sessions" },
  { word: "wget",      hint: "Downloads files from the web non-interactively" },
  { word: "htop",      hint: "An interactive, colorful process viewer with mouse support" },
  { word: "init",      hint: "The first process the kernel starts at boot; ancestor of all others" },
  { word: "lsof",      hint: "Lists all open files and the processes currently using them" },
  { word: "tail",      hint: "Outputs the last lines of a file, commonly used to follow logs" },
  { word: "wall",      hint: "Broadcasts a message to all currently logged-in users" },
  { word: "more",      hint: "A simple pager for reading file output one screen at a time" },
  { word: "fsck",      hint: "Checks and repairs inconsistencies in a filesystem" },
  { word: "jobs",      hint: "Lists background and stopped jobs in the current shell session" },
  { word: "nice",      hint: "Launches a process with a manually specified scheduling priority" },
  { word: "date",      hint: "Displays or sets the system clock and calendar date" },
  { word: "chsh",      hint: "Changes the login shell assigned to a user account" },
  { word: "tcpd",      hint: "Wraps network services to enforce host-based access control" },
  { word: "smss",      hint: "The first user-mode process Windows starts; manages sessions and creates the login environment" },
  { word: "aide",      hint: "Builds a database of file hashes to detect unauthorized changes" },
  { word: "tree",      hint: "Displays the contents of a directory as a visual indented tree" },
  { word: "head",      hint: "Outputs the first several lines of a file or stream" },
  { word: "file",      hint: "Examines a file and classifies its type based on content signatures" },
  { word: "last",      hint: "Shows a history of user logins and system reboots" },
  { word: "stat",      hint: "Displays detailed metadata, permissions, and timestamps for a file" },
  { word: "free",      hint: "Reports total, used, and available system memory at a glance" },
  { word: "node",      hint: "A JavaScript runtime that executes server-side code outside the browser" },
  { word: "uniq",      hint: "Filters out adjacent repeated lines from sorted input" },
  { word: "expr",      hint: "Evaluates arithmetic and string expressions on the command line" },
  { word: "host",      hint: "Performs quick DNS lookups to resolve domain names to addresses" },
  { word: "etcd",      hint: "A distributed key-value store that underpins Kubernetes cluster state" },
  { word: "snap",      hint: "A sandboxed package manager for self-contained Linux applications" },
  { word: "comm",      hint: "Compares two sorted files and shows lines unique to each or shared" },
  { word: "fold",      hint: "Wraps each input line to fit within a specified column width" },
  { word: "join",      hint: "Merges lines from two files based on a shared key field" },
  { word: "wait",      hint: "Pauses shell execution until specified background jobs finish" },
  { word: "sddm",      hint: "A lightweight display manager used as the default login screen for KDE" },
  { word: "nfsd",      hint: "The kernel-level daemon that serves files over the Network File System" },
  { word: "stty",      hint: "Displays or changes terminal line settings and special characters" },
  { word: "gzip",      hint: "Compresses files using the Lempel-Ziv coding algorithm" },
  { word: "lsns",      hint: "Lists all active Linux namespaces and their owning processes" },
  { word: "atop",      hint: "An advanced system and process monitor with historical data logging" },
  { word: "ntpd",      hint: "The daemon that synchronises the system clock with network time servers" },
  { word: "perf",      hint: "A powerful Linux tool for profiling CPU and kernel performance events" },
  { word: "tput",      hint: "Queries and sets terminal capabilities using the terminfo database" },
  { word: "xset",      hint: "Adjusts user preference options for the X display server" },
  { word: "mkfs",      hint: "Creates a new filesystem on a disk partition or block device" },
  { word: "runc",      hint: "The low-level OCI runtime that directly spawns and manages containers" },
  { word: "arch",      hint: "Prints the hardware architecture name of the current machine" },
  { word: "pmap",      hint: "Displays the memory map of a running process and its allocations" },
  { word: "zcat",      hint: "Decompresses and prints gzip-compressed file contents to standard output" },
  { word: "ncat",      hint: "A networking utility for reading, writing, and redirecting data across connections" },
  { word: "dash",      hint: "A fast, minimal POSIX-compliant shell often used for system boot scripts" },
  { word: "tcsh",      hint: "An enhanced C shell with command-line editing and programmable completion" },
  { word: "yara",      hint: "Matches binary patterns and signatures to classify and identify malware samples" },
  { word: "ekrn",      hint: "The core ESET antivirus kernel service that runs real-time file scanning" },
  { word: "zeek",      hint: "A passive network analysis framework that logs traffic for security monitoring" },
  { word: "savd",      hint: "The Sophos Anti-Virus scanning daemon that provides on-access file protection" },
  { word: "wrsa",      hint: "The Webroot SecureAnywhere antivirus process with cloud-based threat detection" },
  { word: "qemu",      hint: "An open-source machine emulator and virtualiser that powers Proxmox VMs" },
  { word: "ceph",      hint: "A distributed storage platform providing block, object, and file storage at scale" },
  { word: "criu",      hint: "Freezes a running process and restores it later, enabling live container migration" },
  { word: "vpxa",      hint: "The vCenter agent on each ESXi host that relays management commands" },
  { word: "dcui",      hint: "The ESXi Direct Console User Interface for local host configuration" },
  { word: "vobd",      hint: "The VMware Observations daemon that monitors and logs ESXi host events" },
  { word: "vpxd",      hint: "The core vCenter Server daemon that manages the entire VMware environment" },
  { word: "vmon",      hint: "The VMware service lifecycle manager that starts and monitors vCenter services" },
  { word: "vlcm",      hint: "The vSphere Lifecycle Manager that handles ESXi patching and image updates" },

  // 5 letters
  { word: "nginx",     hint: "Serves web traffic and proxies requests at high speed" },
  { word: "uname",     hint: "Reports the operating system name and kernel version" },
  { word: "mount",     hint: "Attaches a storage device to the filesystem directory tree" },
  { word: "sleep",     hint: "Suspends execution for a given number of seconds" },
  { word: "touch",     hint: "Creates an empty file or updates its access timestamp" },
  { word: "alias",     hint: "Defines a shorthand name for a longer shell command" },
  { word: "shred",     hint: "Overwrites a file multiple times to prevent data recovery" },
  { word: "rsync",     hint: "Efficiently synchronizes files between two locations" },
  { word: "chown",     hint: "Changes the ownership of a file or directory" },
  { word: "chmod",     hint: "Modifies the read, write, and execute permissions of a file" },
  { word: "dmesg",     hint: "Prints messages from the kernel ring buffer after boot" },
  { word: "nohup",     hint: "Runs a command that stays alive after the terminal closes" },
  { word: "xargs",     hint: "Constructs and executes commands from lines of standard input" },
  { word: "emacs",     hint: "A highly extensible programmer's text editor and computing environment" },
  { word: "httpd",     hint: "The generic HTTP server daemon process name" },
  { word: "xterm",     hint: "A terminal emulator window for the X Window System" },
  { word: "lsblk",     hint: "Lists block storage devices and their partition hierarchy" },
  { word: "udevd",     hint: "The Linux kernel device manager daemon that handles hotplug events" },
  { word: "crond",     hint: "The daemon that reads crontab files and fires scheduled jobs" },
  { word: "fwupd",     hint: "Updates device firmware on Linux systems in the background" },
  { word: "inetd",     hint: "The original internet super-server that spawns other daemons on demand" },
  { word: "acpid",     hint: "Listens for ACPI hardware events like power button and lid close" },
  { word: "route",     hint: "Displays or modifies the kernel IP routing table" },
  { word: "unzip",     hint: "Extracts files from a ZIP archive" },
  { word: "whois",     hint: "Queries registration information for a domain name or IP address" },
  { word: "blkid",     hint: "Identifies block devices and reports their filesystem types and UUIDs" },
  { word: "ifcfg",     hint: "Configures or displays network interface parameters" },
  { word: "lsass",     hint: "Enforces Windows security policy and handles all login authentication" },
  { word: "csrss",     hint: "A critical Windows process that manages console windows and process/thread operations" },
  { word: "clamd",     hint: "The background scanning daemon of a popular open-source antivirus engine" },
  { word: "snort",     hint: "Analyses network packets in real time to detect intrusion attempts" },
  { word: "falco",     hint: "Monitors system calls at runtime to detect unexpected container or process behaviour" },
  { word: "vault",     hint: "Securely stores and tightly controls access to secrets, tokens, and certificates" },
  { word: "ossec",     hint: "A host-based intrusion detection system that monitors logs and file integrity" },
  { word: "wazuh",     hint: "An open-source security platform for threat detection and incident response" },
  { word: "watch",     hint: "Runs a command at regular intervals and displays the updated output" },
  { word: "fdisk",     hint: "Interactively creates, deletes, and modifies disk partition tables" },
  { word: "patch",     hint: "Applies changes from a diff file to update source code or text" },
  { word: "squid",     hint: "A caching proxy server for web content and DNS lookups" },
  { word: "mdadm",     hint: "Creates, monitors, and manages Linux software RAID disk arrays" },
  { word: "cupsd",     hint: "The daemon that manages printers and print job queues on Linux" },
  { word: "named",     hint: "The BIND daemon that answers DNS queries and resolves domain names" },
  { word: "iotop",     hint: "Monitors per-process disk I/O read and write activity in real time" },
  { word: "fuser",     hint: "Identifies which processes are currently using a given file or port" },
  { word: "lsmod",     hint: "Lists all kernel modules currently loaded into memory" },
  { word: "pgrep",     hint: "Searches for running processes by name and prints their process IDs" },
  { word: "pkill",     hint: "Sends a signal to processes selected by name or other attributes" },
  { word: "lspci",     hint: "Lists all PCI devices and controllers attached to the system" },
  { word: "rmmod",     hint: "Removes a loaded module from the running Linux kernel" },
  { word: "xclip",     hint: "Transfers text between the terminal and the X11 system clipboard" },
  { word: "nmcli",     hint: "Controls NetworkManager from the command line to manage connections" },
  { word: "btrfs",     hint: "Manages a modern copy-on-write Linux filesystem with snapshots and checksums" },
  { word: "mstsc",     hint: "The built-in Windows Remote Desktop client for connecting to remote machines" },
  { word: "mdatp",     hint: "The Microsoft Defender for Endpoint command-line tool on Linux and macOS" },
  { word: "sshfs",     hint: "Mounts a remote directory locally over an encrypted SSH connection" },
  { word: "flock",     hint: "Manages file-based advisory locks from shell scripts" },
  { word: "iconv",     hint: "Converts text between different character encodings" },
  { word: "dunst",     hint: "A lightweight notification daemon for Linux desktop environments" },
  { word: "scrot",     hint: "Captures screenshots of the desktop or individual windows on Linux" },
  { word: "zgrep",     hint: "Searches inside compressed files for a pattern without extracting them" },
  { word: "nproc",     hint: "Prints the number of available processing units on the system" },
  { word: "dstat",     hint: "Combines CPU, disk, network, and memory statistics in a single live view" },
  { word: "ipset",     hint: "Manages sets of IP addresses for efficient kernel-level firewall matching" },
  { word: "iperf",     hint: "Measures maximum achievable network throughput between two endpoints" },
  { word: "socat",     hint: "A multipurpose relay for bidirectional data transfer between two channels" },
  { word: "mshta",     hint: "The Windows HTML Application Host that executes HTA files directly" },
  { word: "nmtui",     hint: "A text-based user interface for managing NetworkManager connections" },
  { word: "snapd",     hint: "The background service that manages snap package installation and updates" },
  { word: "kexec",     hint: "Loads and boots directly into a new kernel without firmware restart" },
  { word: "strip",     hint: "Removes symbol and debugging information from compiled binary files" },
  { word: "lynis",     hint: "A security auditing tool that checks Linux systems for hardening opportunities" },
  { word: "esets",     hint: "The ESET file server antivirus daemon that protects Linux systems" },
  { word: "avgnt",     hint: "The Avira antivirus system tray process that shows scan status and alerts" },
  { word: "virsh",     hint: "The command-line shell for managing virtual machines through libvirt" },
  { word: "pveam",     hint: "Downloads and manages Proxmox VE container templates and appliances" },
  { word: "pveum",     hint: "Manages users, groups, and access permissions in a Proxmox VE cluster" },
  { word: "pvesm",     hint: "Configures and manages storage backends in a Proxmox VE environment" },
  { word: "pvesh",     hint: "An interactive shell for calling the Proxmox VE REST API directly" },
  { word: "pvecm",     hint: "Creates, joins, and manages nodes in a Proxmox VE cluster" },
  { word: "lxcfs",     hint: "A FUSE filesystem that gives containers accurate views of CPU and memory usage" },
  { word: "zpool",     hint: "Creates and manages ZFS storage pools built from underlying disk devices" },
  { word: "hostd",     hint: "The ESXi host agent daemon that manages local VMs and host configuration" },
  { word: "sfcbd",     hint: "The CIM broker daemon on ESXi that exposes hardware data to management tools" },
  { word: "lwsmd",     hint: "The Likewise service manager on ESXi for Active Directory domain integration" },
  { word: "vsand",     hint: "The vSAN daemon providing distributed storage across clustered ESXi hosts" },
  { word: "vmcad",     hint: "The VMware Certificate Authority daemon that issues certificates on vCenter" },

  // 6 letters
  { word: "python",    hint: "An interpreted language beloved for its readable syntax" },
  { word: "mysqld",    hint: "The server daemon for a popular open-source relational database" },
  { word: "passwd",    hint: "Lets a user update their login credentials" },
  { word: "screen",    hint: "Keeps terminal sessions alive after you disconnect" },
  { word: "strace",    hint: "Intercepts and records system calls made by a running process" },
  { word: "renice",    hint: "Adjusts the CPU scheduling priority of a running process" },
  { word: "uptime",    hint: "Reports how long the system has been running and current load" },
  { word: "logout",    hint: "Terminates the current user session and closes the shell" },
  { word: "auditd",    hint: "Records security-relevant system events for compliance and forensics" },
  { word: "vmstat",    hint: "Reports virtual memory, CPU, and I/O statistics at a glance" },
  { word: "iostat",    hint: "Shows CPU and disk I/O statistics over time" },
  { word: "polkit",    hint: "Manages authorization requests for privileged system operations" },
  { word: "xinetd",    hint: "An extended internet super-server daemon with fine-grained access control" },
  { word: "syslog",    hint: "Collects and stores system log messages from the kernel and daemons" },
  { word: "puppet",    hint: "Automates configuration management and system state enforcement" },
  { word: "cronie",    hint: "A modern implementation of the cron job scheduling daemon" },
  { word: "dhcpcd",    hint: "A DHCP client daemon that automatically configures network interfaces" },
  { word: "smartd",    hint: "Monitors hard drive health using S.M.A.R.T. diagnostics in the background" },
  { word: "swapon",    hint: "Activates a swap partition or file for use as virtual memory" },
  { word: "wermgr",   hint: "Collects Windows crash data and sends error reports to Microsoft" },
  { word: "parted",    hint: "A disk partitioning tool for creating, resizing, and deleting partitions" },
  { word: "visudo",    hint: "Safely opens the sudoers file in an editor with syntax validation on save" },
  { word: "insmod",    hint: "Loads a single kernel module directly into the running Linux kernel" },
  { word: "chroot",    hint: "Changes the apparent root directory so a process runs in an isolated tree" },
  { word: "logger",    hint: "Sends custom entries to the system log from the command line or a script" },
  { word: "depmod",    hint: "Generates the module dependency database used by the Linux kernel" },
  { word: "sysctl",    hint: "Reads and modifies Linux kernel tunable parameters at runtime" },
  { word: "ctfmon",    hint: "A Windows background process that manages text input and the language bar" },
  { word: "sihost",    hint: "The Windows Shell Infrastructure Host that manages Start menu interactions" },
  { word: "podman",    hint: "A daemonless container engine that runs OCI-compatible containers without root" },
  { word: "vsftpd",    hint: "A small, secure FTP server daemon designed for reliability on Linux" },
  { word: "locate",    hint: "Quickly finds files by name using a pre-built database index" },
  { word: "agetty",    hint: "Manages the login prompt on Linux virtual and serial terminal consoles" },
  { word: "column",    hint: "Formats standard input into neatly aligned table columns" },
  { word: "dxdiag",    hint: "The Windows DirectX diagnostic tool that reports graphics and sound info" },
  { word: "mktemp",    hint: "Creates a temporary file or directory with a unique random name" },
  { word: "chattr",    hint: "Changes extended filesystem attributes on Linux files and directories" },
  { word: "pacman",    hint: "The package manager for Arch Linux and its derivatives" },
  { word: "xinput",    hint: "Lists and configures input devices on the X display server" },
  { word: "xrandr",    hint: "Manages display resolution, rotation, and multi-monitor layout on X11" },
  { word: "chkdsk",    hint: "The Windows utility that scans and repairs filesystem errors on disk" },
  { word: "defrag",    hint: "Reorganises fragmented files on a Windows volume to improve read speed" },
  { word: "finger",    hint: "Looks up information about a user account on a local or remote system" },
  { word: "pstree",    hint: "Displays running processes as a tree of parent-child relationships" },
  { word: "whoami",    hint: "Prints the effective username associated with the current session" },
  { word: "bridge",    hint: "Manages Ethernet bridge devices and VLAN filtering on Linux" },
  { word: "hwinfo",    hint: "Probes hardware and reports detailed device information on Linux" },
  { word: "ranger",    hint: "A terminal-based file manager with vim-like keybindings and file preview" },
  { word: "lsaiso",    hint: "The Windows Credential Guard process that isolates secrets in a secure enclave" },
  { word: "logind",    hint: "Tracks user login sessions, seats, and inhibitor locks on systemd systems" },
  { word: "fsutil",    hint: "A versatile Windows command for querying and configuring filesystem behaviour" },
  { word: "icacls",    hint: "Displays and modifies file and folder access control lists on Windows" },
  { word: "maldet",    hint: "A Linux malware scanner designed to detect threats in shared hosting environments" },
  { word: "falcon",    hint: "The CrowdStrike endpoint detection agent that monitors for advanced threats" },
  { word: "pmxcfs",    hint: "The Proxmox Cluster File System that synchronises config across all nodes" },
  { word: "vzdump",    hint: "The Proxmox backup utility that creates snapshots of VMs and containers" },
  { word: "tshark",    hint: "The terminal-based version of Wireshark for capturing and analysing packets" },
  { word: "nissrv",    hint: "The Windows Defender Network Inspection Service that scans traffic for exploits" },
  { word: "msedge",    hint: "The Microsoft Edge browser process built on the Chromium engine, used for downloading other browsers" },
  { word: "esxtop",    hint: "A real-time performance monitor for ESXi showing CPU, memory, and I/O stats" },
  { word: "esxcli",    hint: "The command-line framework for configuring and querying an ESXi host" },
  { word: "vmafdd",    hint: "The VMware Authentication Framework daemon that manages SSO on vCenter" },
  { word: "vmdird",    hint: "The VMware Directory Service daemon that stores identity data on vCenter" },

  // 7 letters
  { word: "systemd",   hint: "The init system responsible for booting and managing services on modern Linux" },
  { word: "apache2",   hint: "The world's most widely deployed open-source HTTP server process" },
  { word: "svchost",   hint: "A Windows host process that loads multiple DLL-based services" },
  { word: "crontab",   hint: "Edits the table of scheduled recurring automated jobs" },
  { word: "netstat",   hint: "Displays open network connections and listening ports" },
  { word: "rsyslog",   hint: "Collects, filters, and forwards system log messages" },
  { word: "dockerd",   hint: "The background daemon that manages containers and images" },
  { word: "dnsmasq",   hint: "A lightweight DNS forwarder and DHCP server for small networks" },
  { word: "postfix",   hint: "A widely used mail transfer agent for routing and delivering email" },
  { word: "chronyd",   hint: "Keeps the system clock accurately synchronized using NTP" },
  { word: "haproxy",   hint: "A high-performance load balancer for TCP and HTTP traffic" },
  { word: "mariadb",   hint: "The community-developed fork of a popular relational database server" },
  { word: "mongodb",   hint: "A NoSQL document-oriented database server process" },
  { word: "jenkins",   hint: "An open-source automation server for CI/CD pipelines" },
  { word: "grafana",   hint: "A visualization and dashboarding platform for metrics and logs" },
  { word: "kubelet",   hint: "The primary node agent running on each Kubernetes worker node" },
  { word: "autossh",   hint: "Automatically restarts SSH tunnels that drop due to connection issues" },
  { word: "syslogd",   hint: "The traditional Unix daemon that receives and stores system log messages" },
  { word: "lvmetad",   hint: "Caches LVM metadata to speed up volume group activation" },
  { word: "rpcbind",   hint: "Maps RPC program numbers to their network port numbers" },
  { word: "tcpdump",   hint: "Captures raw network packets and displays or saves them for analysis" },
  { word: "openvpn",   hint: "Creates encrypted tunnels between hosts using SSL/TLS" },
  { word: "spoolsv",   hint: "Manages the Windows print queue; frequently targeted in privilege escalation attacks" },
  { word: "stunnel",   hint: "Wraps unencrypted TCP connections inside a TLS tunnel" },
  { word: "openssl",   hint: "A toolkit for SSL/TLS and general-purpose cryptography" },
  { word: "taskmgr",   hint: "The Windows utility for monitoring and killing running processes" },
  { word: "certbot",   hint: "Automatically obtains and renews TLS certificates from a certificate authority" },
  { word: "nessusd",   hint: "The daemon process behind a widely used commercial vulnerability scanner" },
  { word: "openvas",   hint: "The scanner daemon for an open-source vulnerability assessment framework" },
  { word: "ansible",   hint: "An agentless automation tool for configuration management and deployment" },
  { word: "traefik",   hint: "A cloud-native reverse proxy and load balancer for containerised services" },
  { word: "flatpak",   hint: "A framework for distributing sandboxed desktop apps across Linux distros" },
  { word: "conhost",   hint: "The Windows Console Host process that handles command-line window rendering" },
  { word: "dllhost",   hint: "A Windows surrogate process that hosts COM objects and DLL-based services" },
  { word: "msiexec",   hint: "The Windows Installer engine that installs, repairs, and removes MSI packages" },
  { word: "regedit",   hint: "The built-in Windows tool for browsing and editing the system registry" },
  { word: "notepad",   hint: "The basic plain-text editor bundled with every Windows installation" },
  { word: "audiodg",   hint: "The Windows Audio Device Graph process that isolates and processes sound" },
  { word: "consent",   hint: "The Windows process that displays the UAC elevation permission dialog" },
  { word: "connman",   hint: "A lightweight connection manager for networking on embedded Linux systems" },
  { word: "hostapd",   hint: "Turns a wireless network interface into a Wi-Fi access point on Linux" },
  { word: "wscript",   hint: "The Windows Script Host that runs VBScript and JScript files graphically" },
  { word: "cscript",   hint: "The command-line Windows Script Host for running scripts without a GUI" },
  { word: "ethtool",   hint: "Queries and configures network interface card settings and driver parameters" },
  { word: "useradd",   hint: "Creates a new user account on a Linux system with the specified attributes" },
  { word: "userdel",   hint: "Removes a user account and optionally deletes its home directory" },
  { word: "vagrant",   hint: "Creates and manages portable, reproducible virtual development environments" },
  { word: "wininit",   hint: "The early Windows process that launches critical background services at boot" },
  { word: "gparted",   hint: "A graphical partition editor for creating, resizing, and moving disk layouts" },
  { word: "nologin",   hint: "A shell replacement that politely refuses interactive login for service accounts" },
  { word: "unbound",   hint: "A validating, recursive DNS resolver focused on privacy and security" },
  { word: "taskset",   hint: "Pins a process to specific CPU cores by setting its processor affinity mask" },
  { word: "dovecot",   hint: "An open-source IMAP and POP3 email server designed for speed and security" },
  { word: "busybox",   hint: "A single binary providing stripped-down versions of many common Unix utilities" },
  { word: "bcdedit",   hint: "Edits the Windows Boot Configuration Data store for startup settings" },
  { word: "perfmon",   hint: "The Windows performance monitoring and system diagnostics console" },
  { word: "strings",   hint: "Extracts printable character sequences from binary or executable files" },
  { word: "objdump",   hint: "Disassembles object files and displays headers, symbols, and machine code" },
  { word: "timeout",   hint: "Runs a command and kills it if it exceeds a specified time limit" },
  { word: "msmpeng",   hint: "The Windows Defender antimalware engine that scans files and memory for threats" },
  { word: "mssense",   hint: "The Defender for Endpoint sensor that collects endpoint security telemetry" },
  { word: "senseir",   hint: "The Defender for Endpoint module that executes incident response actions" },
  { word: "avguard",   hint: "The Avira real-time protection daemon that intercepts file access on Linux" },
  { word: "bdagent",   hint: "The Bitdefender endpoint agent that coordinates scanning and threat response" },
  { word: "pveceph",   hint: "Installs and manages a Ceph storage cluster from within Proxmox VE" },
  { word: "radosgw",   hint: "The Ceph object gateway that exposes S3 and Swift compatible storage APIs" },
  { word: "vncterm",   hint: "A VNC-based terminal emulator used by Proxmox for container console access" },
  { word: "dumpcap",   hint: "The Wireshark packet capture engine that writes raw traffic to disk" },
  { word: "editcap",   hint: "A Wireshark tool that edits capture files by splitting, trimming, or filtering packets" },

  // 8 letters
  { word: "explorer",  hint: "The Windows graphical desktop shell and file manager" },
  { word: "postgres",  hint: "The backend server process of a popular object-relational database" },
  { word: "chromium",  hint: "The open-source browser engine that powers many modern browsers" },
  { word: "winlogon",  hint: "Handles the Windows secure attention sequence and user login" },
  { word: "iptables",  hint: "Configures the Linux kernel netfilter firewall packet filtering rules" },
  { word: "rabbitmq",  hint: "An Erlang-based message broker and queue server for distributed systems" },
  { word: "dhclient",  hint: "Requests an IP address and network configuration from a DHCP server" },
  { word: "wineboot",  hint: "Initializes and simulates a Windows boot sequence inside the compatibility layer" },
  { word: "svnserve",  hint: "The standalone server daemon for Subversion version control repositories" },
  { word: "nftables",  hint: "The modern Linux packet filtering framework that replaces iptables" },
  { word: "apparmor",  hint: "Confines programs to a limited set of resources using per-process security profiles" },
  { word: "suricata",  hint: "A high-performance network intrusion detection, prevention, and monitoring engine" },
  { word: "rkhunter",  hint: "Scans for rootkits, backdoors, and suspicious local exploits" },
  { word: "tripwire",  hint: "Detects unauthorised file changes by comparing against a known-good baseline" },
  { word: "seclogon",  hint: "A Windows service that allows processes to be started under different credentials" },
  { word: "ntoskrnl",  hint: "The core Windows kernel image responsible for hardware abstraction and system calls" },
  { word: "corosync",  hint: "A cluster communication engine that keeps nodes synchronised and aware of each other" },
  { word: "schtasks",  hint: "The Windows command-line tool for creating and managing scheduled tasks" },
  { word: "pipewire",  hint: "A modern Linux multimedia server that handles both audio and video streams" },
  { word: "collectd",  hint: "A daemon that collects system performance metrics and writes them to storage" },
  { word: "sendmail",  hint: "One of the oldest and most widely deployed mail transfer agents on Unix" },
  { word: "lighttpd",  hint: "A lightweight, high-performance web server optimised for speed-critical environments" },
  { word: "virtlogd",  hint: "A libvirt daemon that manages and preserves log files for virtual machines" },
  { word: "telegraf",  hint: "A plugin-driven metrics collection agent that feeds data into time-series databases" },
  { word: "nslookup",  hint: "An interactive tool that queries DNS servers to resolve names and addresses" },
  { word: "taskhost",  hint: "A generic Windows host process that runs DLL-based scheduled background tasks" },
  { word: "msconfig",  hint: "The Windows utility for managing startup programs and boot configuration" },
  { word: "modprobe",  hint: "Loads a Linux kernel module along with all of its dependencies" },
  { word: "groupadd",  hint: "Creates a new group account on a Linux system" },
  { word: "werfault",  hint: "The Windows Error Reporting process that captures crash diagnostics from apps" },
  { word: "diskpart",  hint: "The interactive Windows command-line tool for managing disk partitions" },
  { word: "robocopy",  hint: "A robust Windows file-copy utility designed for reliable large-scale transfers" },
  { word: "valgrind",  hint: "A memory debugging framework that detects leaks and invalid accesses in programs" },
  { word: "loginctl",  hint: "Inspects and manages user sessions and seats through systemd" },
  { word: "ldconfig",  hint: "Rebuilds the shared library cache so the dynamic linker can find new libraries" },
  { word: "cleanmgr",  hint: "The Windows Disk Cleanup utility that removes temporary and cached files" },
  { word: "eventvwr",  hint: "The Windows Event Viewer for browsing system, security, and application logs" },
  { word: "dropbear",  hint: "A lightweight SSH server and client designed for embedded and low-memory systems" },
  { word: "kthreadd",  hint: "The Linux kernel thread daemon that spawns all other kernel-level threads" },
  { word: "logwatch",  hint: "Analyses system logs and produces a summarised daily report for the admin" },
  { word: "ntrtscan",  hint: "The Trend Micro real-time scan engine that checks files on access for malware" },
  { word: "cbagentd",  hint: "The Carbon Black endpoint agent daemon that streams process events for analysis" },
  { word: "mbamtray",  hint: "The Malwarebytes system tray process that provides scan status and quick actions" },
  { word: "cmdagent",  hint: "The Comodo Internet Security agent that coordinates firewall and antivirus" },
  { word: "clamscan",  hint: "The standalone ClamAV scanner that checks files for viruses without the daemon" },
  { word: "pveproxy",  hint: "The Proxmox VE HTTPS proxy that serves the web console and REST API" },
  { word: "pvestatd",  hint: "Collects and broadcasts node and VM status across a Proxmox VE cluster" },
  { word: "qmeventd",  hint: "Handles QEMU virtual machine lifecycle events for Proxmox backup integration" },
  { word: "libvirtd",  hint: "The libvirt management daemon that provides a unified API for virtual machines" },
  { word: "mergecap",  hint: "A Wireshark tool that combines multiple packet capture files into one" },
  { word: "mpcmdrun",  hint: "The Windows Defender command-line tool for managing scans, updates, and exclusions" },
  { word: "iexplore",  hint: "The Internet Explorer browser process, once the dominant way to browse the web" },
  { word: "vmkernel",  hint: "The ESXi hypervisor microkernel that directly manages hardware and virtual machines" },

  // 9 letters
  { word: "memcached",  hint: "Stores frequently accessed data in memory to reduce database load" },
  { word: "firewalld",  hint: "The dynamic firewall management daemon on modern Linux systems" },
  { word: "logrotate",  hint: "Rotates, compresses, and manages old log files automatically" },
  { word: "wireshark",  hint: "Captures and dissects network packets with a rich protocol analyser" },
  { word: "windefend",  hint: "The Windows Defender antivirus service that scans for malware in real time" },
  { word: "wireguard",  hint: "A modern, high-performance VPN protocol built into the Linux kernel" },
  { word: "timeshift",  hint: "Creates snapshots of the Linux filesystem for easy backup and rollback" },
  { word: "terraform",  hint: "Provisions and manages cloud infrastructure using declarative configuration files" },
  { word: "multipath",  hint: "Manages redundant storage paths so devices stay accessible if one link fails" },
  { word: "cassandra",  hint: "A distributed NoSQL database designed for high availability and massive scalability" },
  { word: "zookeeper",  hint: "A coordination service that manages configuration for distributed systems" },
  { word: "systemctl",  hint: "The primary command for managing systemd services, targets, and units" },
  { word: "apachectl",  hint: "The control interface for starting, stopping, and restarting the Apache server" },
  { word: "syncthing",  hint: "A peer-to-peer tool that keeps folders synchronised across multiple devices" },
  { word: "saslauthd",  hint: "A daemon that handles plaintext SASL authentication for mail and LDAP services" },
  { word: "mitmproxy",  hint: "An interactive TLS-capable proxy for inspecting and modifying HTTP traffic" },
  { word: "clamdscan",  hint: "Sends files to the ClamAV daemon for on-demand virus and malware scanning" },
  { word: "borgmatic",  hint: "Automates backup creation, pruning, and consistency checks with BorgBackup" },
  { word: "freshclam",  hint: "The ClamAV updater daemon that downloads the latest virus signature databases" },
  { word: "falconctl",  hint: "The command-line tool for configuring and managing the CrowdStrike Falcon sensor" },
  { word: "sentineld",  hint: "The SentinelOne autonomous endpoint protection agent daemon on Linux" },
  { word: "pvedaemon",  hint: "The core Proxmox VE daemon that handles cluster-wide API and task operations" },
  { word: "vpostgres",  hint: "The embedded PostgreSQL instance storing all vCenter inventory and configuration" },
  { word: "vsanmgmtd",  hint: "The vSAN management daemon that handles storage policy and cluster operations" },

  // 10 letters
  { word: "keepalived",  hint: "Provides high availability and load balancing via VRRP" },
  { word: "containerd",  hint: "The industry-standard container runtime used by Docker and Kubernetes" },
  { word: "pulseaudio",  hint: "The sound server daemon that routes audio between applications on Linux" },
  { word: "prometheus",  hint: "A monitoring system that scrapes, stores, and queries time-series metrics" },
  { word: "powershell",  hint: "A cross-platform command shell and scripting language from Microsoft" },
  { word: "journalctl",  hint: "Queries and filters structured log entries from the systemd journal" },
  { word: "bluetoothd",  hint: "The Linux daemon that manages Bluetooth device pairing and connections" },
  { word: "traceroute",  hint: "Maps the network path packets take to reach a remote host hop by hop" },
  { word: "resolvectl",  hint: "Manages DNS settings and queries through the systemd-resolved service" },
  { word: "networkctl",  hint: "Displays and manages network link state through systemd-networkd" },
  { word: "machinectl",  hint: "Manages local virtual machines and containers registered with systemd" },
  { word: "squidguard",  hint: "A URL filter and redirector plugin that enforces web access policies for Squid" },
  { word: "chkrootkit",  hint: "Scans a Linux system for known rootkit signatures and suspicious modifications" },
  { word: "spiceproxy",  hint: "The Proxmox SPICE protocol proxy that streams VM console sessions to browsers" },
  { word: "wdavdaemon",  hint: "The Microsoft Defender for Endpoint daemon that runs real-time protection on Linux" },
  { word: "rhttpproxy",  hint: "The reverse HTTP proxy on ESXi and vCenter that routes web and API traffic" },
  { word: "vmkfstools",  hint: "The ESXi command-line tool for creating, cloning, and managing virtual disks" },
];
